### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by gausoft** [mohamedHassanKa/ProductAppCourse#2]
I'm getting this type of error and I don't find solution yet. What is the cause of that?

![Screenshot_20191220-065317](https://user-images.githubusercontent.com/26385667/71236110-00445980-22f6-11ea-9830-a015e0e31031.png)

 ```
The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#dd569):
type 'List<dynamic>' is not a subtype of type 'String'
```

**Comment by mohamedHassanKa** [comment]
soory for late response . should be working fine now . this happened because my database was open so some people could add other  attributes and this caused the app to have extra  attributed not defined in the model
